name: hello world
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check the code
        uses: actions/checkout@v4
      - name: print index.html
        run: cat ds.yml
      
